"""Sincronizar modelos y agregar modo

Revision ID: 5ad0827b2607
Revises: add_modo_field
Create Date: 2025-08-11 09:50:56.269271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad0827b2607'
down_revision = 'add_modo_field'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'admin_user', ['username'])
    op.add_column('attendance', sa.Column('modo', sa.String(length=10), nullable=True))
    op.alter_column('attendance', 'is_late',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attendance', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('employee', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('employee', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('employee', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('attendance', 'longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attendance', 'latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attendance', 'is_late',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('attendance', 'modo')
    op.drop_constraint(None, 'admin_user', type_='unique')
    op.alter_column('admin_user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
