"""add is_late to attendance

Revision ID: 5b80b5866026
Revises: 5b05bf5ba31c
Create Date: 2025-07-25 10:34:15.332107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b80b5866026'
down_revision = '5b05bf5ba31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_late', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('is_late')

    # ### end Alembic commands ###
